#!/usr/bin/env python3

import sys

logfile = sys.argv[1]
with open(logfile) as f:
  for line in f:
    if "CRON" not in line:
      continue
    print(line.strip())
    
  #using a regular expression
  
  import re
  pattern = r"USER \((\(w+)\)$"
  line = "Jul 6 14:04:01 computer.name...."
  result = re.search(pattern, line)
  print(result[1])
  
  #combined creates
#!/usr/bin/env python3
import re
import sys

logfile = sys.argv[1]
usernames = {}
with open(logfile) as f:
  for line in f:
    if "CRON" not in line:
      continue
    pattern = r"USER \((\(w+)\)$"
  result = re.search(pattern, line)
  if result is None:
      continue
  name = result[1]
  usernames[name] = usernames.get(name, 0) + 1
  #print(result[1])
print(usernames)
